# Generated by Django 3.0 on 2019-12-13 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('use_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('active', models.BooleanField()),
                ('discount', models.CharField(choices=[('ringit', 'RM 10 off'), ('percentage', '10% off')], max_length=32)),
            ],
        ),
    ]
