# Generated by Django 3.0 on 2019-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='discount',
            field=models.CharField(choices=[('RM 10 off', 'ringit'), ('10% off', 'percentage')], default='ringit', max_length=32),
        ),
    ]
