# Generated by Django 3.0 on 2019-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20191213_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='discount',
            field=models.CharField(choices=[('RM 10 off', 'RM 10 off'), ('10% off', '10% off')], default='RM 10 off', max_length=32),
        ),
    ]
