# Generated by Django 3.0 on 2019-12-13 14:05

import django.core.validators
from django.db import migrations, models
import vouchers.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20191213_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='use_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
