# Generated by Django 3.0 on 2019-12-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_auto_20191213_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vouchers',
            new_name='Voucher',
        ),
    ]
