# Generated by Django 3.0 on 2020-01-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_auto_20191214_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.CharField(choices=[('RM', 'RM'), ('%', '%')], default='RM 10 off', max_length=32),
        ),
    ]
