# Generated by Django 3.0 on 2020-01-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_auto_20200112_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
